version: '3'

services:
  api:
    build: .
    ports:
      - "6000:6000"
    env_file:
      - .env
    depends_on:
      - database
    restart: always
    networks:
      - api_network

  database:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    networks:
      - api_network
    command: ["--bind_ip_all"]

networks:
  api_network:

volumes:
  mongo_data: