version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    restart: always
    networks:
      - api_network

    database:
      image: api_db_mongo:7.0
      ports:
        - "27017:27017"
      volumes:
       - mongo_data:/data/db

      enviroment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      restart: always
      networks:
        - api_network
  
  networks:
    api_network:

  volumes:
    mongo_data:
